name: Build and deploy Python app to Azure Web App - DDB1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Run tests here

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_39E2B52CE0254A4C8A43ED3CA9FA11D6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F90EC04816C740659CD955D2234BCB51 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C8627BAB2B8646209842F70E76817926 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'DDB1'
          slot-name: 'Production'
          package: release.zip
